### ISSUE TITLE
PDCIDFontType2 - Could not read embedded OTF for font TimesNewRoman0

### ISSUE THREAD

**Issue by 5hivams** [JonathanLink/PDFLayoutTextStripper#14]
Hi,

I am trying to extract data from attached PDF as you mentioned in your sample code but I am getting font error. just fyi I am using pdfbox 2.0.6

Here below is the log:

[main] WARN org.apache.pdfbox.pdmodel.font.FileSystemFontProvider - New fonts found, font cache will be re-built
[main] WARN org.apache.pdfbox.pdmodel.font.FileSystemFontProvider - Building on-disk font cache, this may take a while
[main] WARN org.apache.pdfbox.pdmodel.font.FileSystemFontProvider - Finished building on-disk font cache, found 463 fonts
[main] WARN org.apache.pdfbox.pdmodel.font.PDCIDFontType2 - Could not read embedded OTF for font TimesNewRoman0
java.io.EOFException
	at org.apache.fontbox.ttf.MemoryTTFDataStream.readSignedShort(MemoryTTFDataStream.java:138)
	at org.apache.fontbox.ttf.OS2WindowsMetricsTable.read(OS2WindowsMetricsTable.java:827)
	at org.apache.fontbox.ttf.TrueTypeFont.readTable(TrueTypeFont.java:335)
	at org.apache.fontbox.ttf.TTFParser.parseTables(TTFParser.java:174)
	at org.apache.fontbox.ttf.TTFParser.parse(TTFParser.java:150)
	at org.apache.fontbox.ttf.OTFParser.parse(OTFParser.java:79)
	at org.apache.fontbox.ttf.OTFParser.parse(OTFParser.java:27)
	at org.apache.fontbox.ttf.TTFParser.parse(TTFParser.java:106)
	at org.apache.fontbox.ttf.OTFParser.parse(OTFParser.java:73)
	at org.apache.pdfbox.pdmodel.font.PDCIDFontType2.<init>(PDCIDFontType2.java:117)
	at org.apache.pdfbox.pdmodel.font.PDCIDFontType2.<init>(PDCIDFontType2.java:69)
	at org.apache.pdfbox.pdmodel.font.PDFontFactory.createDescendantFont(PDFontFactory.java:125)
	at org.apache.pdfbox.pdmodel.font.PDType0Font.<init>(PDType0Font.java:129)
	at org.apache.pdfbox.pdmodel.font.PDFontFactory.createFont(PDFontFactory.java:83)
	at org.apache.pdfbox.pdmodel.PDResources.getFont(PDResources.java:143)
	at org.apache.pdfbox.contentstream.operator.text.SetFontAndSize.process(SetFontAndSize.java:60)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processOperator(PDFStreamEngine.java:838)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processStreamOperators(PDFStreamEngine.java:495)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processStream(PDFStreamEngine.java:469)
	at org.apache.pdfbox.contentstream.PDFStreamEngine.processPage(PDFStreamEngine.java:150)
	at org.apache.pdfbox.text.LegacyPDFStreamEngine.processPage(LegacyPDFStreamEngine.java:139)
	at org.apache.pdfbox.text.PDFTextStripper.processPage(PDFTextStripper.java:391)
	at PDFLayoutTextStripper.processPage(PDFLayoutTextStripper.java:81)
	at org.apache.pdfbox.text.PDFTextStripper.processPages(PDFTextStripper.java:319)
	at org.apache.pdfbox.text.PDFTextStripper.writeText(PDFTextStripper.java:266)
	at org.apache.pdfbox.text.PDFTextStripper.getText(PDFTextStripper.java:227)
	at Scan.readPDF(Scan.java:130)
	at Scan.main(Scan.java:40)
[main] WARN org.apache.pdfbox.pdmodel.font.PDCIDFontType2 - Using fallback font LiberationSans for CID-keyed TrueType font TimesNewRoman0
[main] WARN org.apache.pdfbox.pdmodel.font.PDType0Font - No Unicode mapping for CID+32 (32) in font TimesNewRoman0
[main] WARN org.apache.pdfbox.pdmodel.font.PDCIDFontType2 - Failed to find a character mapping for 32 in TimesNewRoman0
java.lang.IllegalArgumentException: Comparison method violates its general contract!
	at java.util.TimSort.mergeHi(TimSort.java:895)
	at java.util.TimSort.mergeAt(TimSort.java:512)
	at java.util.TimSort.mergeCollapse(TimSort.java:437)
	at java.util.TimSort.sort(TimSort.java:241)
	at java.util.Arrays.sort(Arrays.java:1435)
	at java.util.Collections.sort(Collections.java:230)
	at PDFLayoutTextStripper.sortTextPositionList(PDFLayoutTextStripper.java:114)
	at PDFLayoutTextStripper.writePage(PDFLayoutTextStripper.java:92)
	at org.apache.pdfbox.text.PDFTextStripper.processPage(PDFTextStripper.java:392)
	at PDFLayoutTextStripper.processPage(PDFLayoutTextStripper.java:81)
	at org.apache.pdfbox.text.PDFTextStripper.processPages(PDFTextStripper.java:319)
	at org.apache.pdfbox.text.PDFTextStripper.writeText(PDFTextStripper.java:266)
	at org.apache.pdfbox.text.PDFTextStripper.getText(PDFTextStripper.java:227)
	at Scan.readPDF(Scan.java:130)
	at Scan.main(Scan.java:40)

[CLMS#56589936#2.PDF](https://github.com/JonathanLink/PDFLayoutTextStripper/files/1193321/CLMS.56589936.2.PDF)

**Comment by JonathanLink** [comment]
Thank you for reporting that bug, I appreciate. I have fixed it. See release v2.2.1
