### ISSUE TITLE
PDFLayoutTextStripper StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by gustavopiucco** [JonathanLink/PDFLayoutTextStripper#20]
I am using PDFLayoutTextStripper with some PDF's and works perfecly, but today I came across the attached PDF returning the following exception:

java.lang.StringIndexOutOfBoundsException: String index out of range: -1

	at java.lang.String.charAt(String.java:658)
	at com.xxx.pdfbox.TextLine.isSpaceCharacterAtIndex(TextLine.java:58)

[tim.pdf](https://github.com/JonathanLink/PDFLayoutTextStripper/files/1924042/tim.pdf)

**Comment by JonathanLink** [comment]
Hello,
Thank you for reporting that bug. I fixed it in the next version that I am going to release soon.
At the moment you can tried to pull the code of the _dev_ branch here: https://github.com/JonathanLink/PDFLayoutTextStripper/tree/dev

**Comment by gustavopiucco** [comment]
Hello Jonathan,

I tested with the dev branch and the exception is not thrown anymore, but the output only shows from page 20~25+

**Comment by abhineet255** [comment]
Hi Jonathan,

Did you end up resolving the issue and releasing an updated version? I am facing this issue with all the PDFs I am trying to parse (they are all generated by the same vendor for different users).
